In [4]:
def recurse(str1, str2):
    #alignment with minimal edit distance
    #print('%s vs %s' %(str1,str2))
    if len(str1)==0:
        return(len(str2))
    elif len(str2)==0:
        return(len(str1))
    else:
        dist= min(recurse(str1[:-1],str2[:-1]) + 0 if str1[-1]==str2[-1] else 1,
            recurse(str1[:-1],str2)+1,
            recurse(str1,str2[:-1])+1)
        return(dist)

str1= 'AA'
str2= 'ATA'

dist= recurse(str1,str2)
print('dist %i' %dist)

dist 1


In [4]:
import numpy as np

def fill_matrix(str1, str2):
    #fill the dynamic programming matrix
    mtx= np.empty( shape= (len(str1)+1,len(str2)+1), dtype='i')
    mtx[:,0]= range(len(str1)+1)
    mtx[0,:]= range(len(str2)+1)
    for i in range(1,len(str1)+1):
        for j in range(1,len(str2)+1):
            print('i: %i, j: %i' %(i, j))
            currChar_penalty= 0 if str1[i-1] == str2[j-1] else 1
            mtx[i,j]= min( currChar_penalty + mtx[i-1, j-1], #add to i and j
                            1 + mtx[i-1, j], #add to i
                            1 + mtx[i, j-1] ) #add to j
        print(mtx)

str1= 'AA'
str2= 'ATA'
fill_matrix(str1, str2)

i: 1, j: 1
i: 1, j: 2
i: 1, j: 3
[[0 1 2 3]
 [1 0 1 2]
 [2 1 1 1]]
i: 2, j: 1
i: 2, j: 2
i: 2, j: 3
[[0 1 2 3]
 [1 0 1 2]
 [2 1 1 1]]
